<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Leave Permission Letter</title>
  <style>
    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 12pt;
      margin: 40px;
      line-height: 1.6;
      color: #000;
    }

    .header {
      text-align: center;
      margin-bottom: 30px;
    }

    .header h2 {
      margin: 0;
      font-size: 18pt;
    }

    .line {
      border-top: 2px solid #000;
      margin: 10px 0 30px 0;
    }

    .content {
      text-align: justify;
    }

    .signature {
      margin-top: 60px;
      text-align: right;
    }

    .signature p {
      margin-bottom: 80px;
    }

    .footer {
      text-align: center;
      font-size: 10pt;
      margin-top: 50px;
      color: #777;
    }
  </style>
</head>
<body>
  <div class="header">
    <h2>Leave Permission Letter</h2>
    <p>Dormitory Management System</p>
  </div>

  <div class="line"></div>

  <div class="content">
    <p>
      This is to formally inform that the student named <strong>{{ $permission->student->name }}</strong> with NIM <strong>{{ $permission->student->nim }}</strong>
      is requesting a leave for the purpose of
      <strong>{{ strtoupper($permission->type) === 'IB' ? 'Overnight Leave (IB)' : 'Day Leave' }}</strong>.
    </p>

    <p>
      The leave is scheduled to begin on <strong>{{ \Carbon\Carbon::parse($permission->start_date)->format('d M Y') }}</strong>
      @if($permission->start_date !== $permission->end_date)
        and end on <strong>{{ \Carbon\Carbon::parse($permission->end_date)->format('d M Y') }}</strong>.
      @else
        .
      @endif
    </p>

    <p>
      The reason stated for this leave request is: <em>"{{ $permission->reason }}"</em>.
    </p>

    @if ($permission->status === 'approved')
      <p>This leave request has been <strong>APPROVED</strong>.</p>
    @elseif ($permission->status === 'rejected')
      <p>
        This leave request has been <strong>REJECTED</strong>. <br>
        Rejection reason: <em>{{ $permission->rejection_reason }}</em>
      </p>
    @else
      <p>This leave request is currently <strong>PENDING</strong> for approval.</p>
    @endif
  </div>

  <div class="signature">
    <p>Approved by,</p>
    <p>__________</p>
  </div>

  <div class="footer">
    Generated by Dormitory Management System
  </div>
</body>
</html>
